### ISSUE TITLE
Some fixes

### ISSUE THREAD

**Issue by AHOHNMYC** [Redcrafter/Bandcamp-Volume-Bar#1]
Good day. I like your script, but it won't work on some my browsers, so I fixed it.
`GM_addStyle` don't exist in some script managers, `pos.x` causes error, value from `localStorage` reads as string, `var` used instead of `let` in 2k18 and so on.
Here is update: https://paste.debian.net/plainh/8e291eed

**Comment by Redcrafter** [comment]
Thank you for your contribution. I added your Bugfixes in 5ddf2302db92b1d567349bb41228d9b081d14d3f.
Though i wont use `let` and `const` for a bit more backwards compatibility.
And next time please create a pull request for your fixes.
